
package ComponentOther;

import Helper.XShareHelper;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JProgressBar;
/**
 *
 * @author ASUS
 */
public class HelloJPanel extends javax.swing.JPanel{

    public JProgressBar getPgbLoading() {
        return pgbLoading;
    }

    public void setPgbLoading(JProgressBar pgbLoading) {
        this.pgbLoading = pgbLoading;
    }

    public JLabel getLblImage() {
        return lblImage;
    }

    public void setLblImage(JLabel lblImage) {
        this.lblImage = lblImage;
    }

    
    public HelloJPanel() {
        initComponents();
        this.setVisible(false);
        lblImage.setBounds(-480, 430, 455, 273);
        init();
    }

    private void init(){
        ImageIcon icon = new ImageIcon("src/Image/hello.jpg");
        Image image = icon.getImage();
        ImageIcon imageScaled = new ImageIcon(image.getScaledInstance(1280, 720, Image.SCALE_SMOOTH));
        lblBackground.setIcon(imageScaled);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pgbLoading = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setBackground(new java.awt.Color(149, 145, 74));
        setLayout(new java.awt.BorderLayout());

        pgbLoading.setPreferredSize(new java.awt.Dimension(146, 18));
        add(pgbLoading, java.awt.BorderLayout.PAGE_END);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/giphy.gif"))); // NOI18N
        jPanel1.add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(-410, 430, 455, 273));

        lblBackground.setBackground(new java.awt.Color(67, 18, 182));
        lblBackground.setOpaque(true);
        jPanel1.add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 700));

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblImage;
    private javax.swing.JProgressBar pgbLoading;
    // End of variables declaration//GEN-END:variables
}
